

##NAMA : Hilda Tri F H
##NIM  : 22510207111023
##Kelas : MLOps - A



In [91]:
import pandas as pd
import numpy as np

##Pengumpulan dan Persiapan Data:

In [92]:
!wget https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv

--2024-09-04 19:09:32--  https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3975 (3.9K) [text/plain]
Saving to: ‘iris.csv.2’

iris.csv.2          100%[===================>]   3.88K  --.-KB/s    in 0s      

2024-09-04 19:09:32 (39.3 MB/s) - ‘iris.csv.2’ saved [3975/3975]



In [93]:
data = pd.read_csv('iris.csv')

##Cek isi dataset

In [94]:
data.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

##Missing value

In [95]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

missing_values = data.isnull().sum()
print("\nJumlah nilai yang hilang di setiap kolom:\n", missing_values)

numeric_cols = data.select_dtypes(include=[np.number]).columns
data[numeric_cols] = data[numeric_cols].fillna(data[numeric_cols].mean())

missing_values_after = data.isnull().sum()
print("\nJumlah nilai yang hilang setelah pengisian:\n", missing_values_after)

scaler = StandardScaler()
data_scaled = pd.DataFrame(scaler.fit_transform(data[numeric_cols]), columns=numeric_cols)

data_scaled['variety'] = data['variety']
print("\nData setelah normalisasi:\n", data_scaled.head())



Jumlah nilai yang hilang di setiap kolom:
 sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

Jumlah nilai yang hilang setelah pengisian:
 sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

Data setelah normalisasi:
    sepal.length  sepal.width  petal.length  petal.width variety
0     -0.900681     1.019004     -1.340227    -1.315444  Setosa
1     -1.143017    -0.131979     -1.340227    -1.315444  Setosa
2     -1.385353     0.328414     -1.397064    -1.315444  Setosa
3     -1.506521     0.098217     -1.283389    -1.315444  Setosa
4     -1.021849     1.249201     -1.340227    -1.315444  Setosa


##Pelatihan Model

In [96]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

In [97]:
X = data.iloc[:, :-1]
y = data['variety']

In [98]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [99]:
#confersi label
y_train = pd.factorize(y_train)[0]
y_test = pd.factorize(y_test)[0]

##Melatih Model Logistic Regression

In [100]:
# Inisialisasi dan latih model Logistic Regression
logreg_model = LogisticRegression(random_state=42)
logreg_model.fit(X_train, y_train)

y_pred_logreg = logreg_model.predict(X_test)

# Evaluasi model
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_logreg))
print("Classification Report:\n", classification_report(y_test, y_pred_logreg))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_logreg))


Logistic Regression Accuracy: 0.36666666666666664
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         9
           1       0.00      0.00      0.00        10
           2       1.00      1.00      1.00        11

    accuracy                           0.37        30
   macro avg       0.33      0.33      0.33        30
weighted avg       0.37      0.37      0.37        30

Confusion Matrix:
 [[ 0  9  0]
 [10  0  0]
 [ 0  0 11]]


##Melatih Model Decision Tree

In [101]:
# Inisialisasi dan latih model Decision Tree
tree_model = DecisionTreeClassifier(random_state=42)
tree_model.fit(X_train, y_train)

y_pred_tree = tree_model.predict(X_test)

# Evaluasi model
print("\nDecision Tree Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Classification Report:\n", classification_report(y_test, y_pred_tree))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_tree))


Decision Tree Accuracy: 0.36666666666666664
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         9
           1       0.00      0.00      0.00        10
           2       1.00      1.00      1.00        11

    accuracy                           0.37        30
   macro avg       0.33      0.33      0.33        30
weighted avg       0.37      0.37      0.37        30

Confusion Matrix:
 [[ 0  9  0]
 [10  0  0]
 [ 0  0 11]]


##KNN (l K-Nearest Neighbors)

In [102]:
# Inisialisasi dan latih model K-Nearest Neighbors (KNN)
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

y_pred_knn = knn_model.predict(X_test)

# Evaluasi model
print("\nK-Nearest Neighbors (KNN) Accuracy:", accuracy_score(y_test, y_pred_knn))
print("Classification Report:\n", classification_report(y_test, y_pred_knn))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))



K-Nearest Neighbors (KNN) Accuracy: 0.36666666666666664
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         9
           1       0.00      0.00      0.00        10
           2       1.00      1.00      1.00        11

    accuracy                           0.37        30
   macro avg       0.33      0.33      0.33        30
weighted avg       0.37      0.37      0.37        30

Confusion Matrix:
 [[ 0  9  0]
 [10  0  0]
 [ 0  0 11]]


##Evaluasi Model

In [103]:
import json
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

def evaluate_model(y_test, y_pred, model_name):
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    evaluation_results = {
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1
    }

    return evaluation_results

    logreg_results = evaluate_model(y_test, y_pred_logreg, "Logistic Regression")
    tree_results = evaluate_model(y_test, y_pred_tree, "Decision Tree")
    knn_results = evaluate_model(y_test, y_pred_knn, "K-Nearest Neighbors")

    all_results = {
    "Logistic Regression": logreg_results,
    "Decision Tree": tree_results,
    "K-Nearest Neighbors": knn_results
}

    with open("evaluation_results.json", "w") as json_file:
        json.dump(all_results, json_file, indent=4)

    print("Evaluation results saved to evaluation_results.json")


In [104]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Mengevaluasi setiap model
logreg_results = evaluate_model(y_test, y_pred_logreg, "Logistic Regression")
tree_results = evaluate_model(y_test, y_pred_tree, "Decision Tree")
knn_results = evaluate_model(y_test, y_pred_knn, "K-Nearest Neighbors")

# Menggabungkan hasil evaluasi dari semua model
all_results = {
    "Logistic Regression": logreg_results,
    "Decision Tree": tree_results,
    "K-Nearest Neighbors": knn_results
}

# Menyimpan hasil evaluasi dalam format teks
with open('model_evaluation_results.txt', 'w') as txt_file:
    for model_name, results in all_results.items():
        txt_file.write(f"Model: {results['Model']}\n")
        txt_file.write(f"Accuracy: {results['Accuracy']:.4f}\n")
        txt_file.write(f"Precision: {results['Precision']:.4f}\n")
        txt_file.write(f"Recall: {results['Recall']:.4f}\n")
        txt_file.write(f"F1 Score: {results['F1 Score']:.4f}\n")
        txt_file.write("\n")

print("Hasil evaluasi model telah disimpan ke 'model_evaluation_results.txt'")

Hasil evaluasi model telah disimpan ke 'model_evaluation_results.txt'


##Deployment Model

In [105]:
import joblib
# Menyimpan model Decision Tree
joblib.dump(tree_model, 'tree_model.pkl')
# Menyimpan model K-Nearest Neighbors
joblib.dump(knn_model, 'knn_model.pkl')

print("Model telah disimpan menggunakan joblib.")

Model telah disimpan menggunakan joblib.


In [106]:
import pickle
# Menyimpan model Logistic Regression
with open('logreg_model.pkl', 'wb') as file:
    pickle.dump(logreg_model, file)
# Menyimpan model Decision Tree
with open('tree_model.pkl', 'wb') as file:
    pickle.dump(tree_model, file)
# Menyimpan model K-Nearest Neighbors
with open('knn_model.pkl', 'wb') as file:
    pickle.dump(knn_model, file)

print("Model telah disimpan menggunakan pickle.")

Model telah disimpan menggunakan pickle.


##Makefile

In [107]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# Memuat data
data = pd.read_csv('iris.csv')

# Memisahkan fitur dan label
X = data.iloc[:, :-1]
y = data['variety']

# Normalisasi fitur
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Menyimpan data yang telah diproses
processed_data = pd.DataFrame(X_scaled, columns=data.columns[:-1])
processed_data['variety'] = y
processed_data.to_csv('processed_data.csv', index=False)

In [108]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
import joblib

# Memuat data yang telah diproses
data = pd.read_csv('processed_data.csv')
X = data.iloc[:, :-1]
y = data['variety']

# Membagi data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Melatih model
logreg_model = LogisticRegression(random_state=42)
logreg_model.fit(X_train, y_train)

tree_model = DecisionTreeClassifier(random_state=42)
tree_model.fit(X_train, y_train)

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

# Menyimpan model
joblib.dump(logreg_model, 'logreg_model.pkl')
joblib.dump(tree_model, 'tree_model.pkl')
joblib.dump(knn_model, 'knn_model.pkl')

['knn_model.pkl']

In [109]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import joblib

# Memuat data yang telah diproses
data = pd.read_csv('processed_data.csv')
X = data.iloc[:, :-1]
y = data['variety']

# Membagi data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Memuat model
logreg_model = joblib.load('logreg_model.pkl')
tree_model = joblib.load('tree_model.pkl')
knn_model = joblib.load('knn_model.pkl')

# Evaluasi model
def evaluate_model(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    return {
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1
    }

# Evaluasi model
logreg_results = evaluate_model(logreg_model, X_test, y_test, "Logistic Regression")
tree_results = evaluate_model(tree_model, X_test, y_test, "Decision Tree")
knn_results = evaluate_model(knn_model, X_test, y_test, "K-Nearest Neighbors")

# Menyimpan hasil evaluasi
with open('model_evaluation_results.txt', 'w') as f:
    for results in [logreg_results, tree_results, knn_results]:
        f.write(f"Model: {results['Model']}\n")
        f.write(f"Accuracy: {results['Accuracy']:.4f}\n")
        f.write(f"Precision: {results['Precision']:.4f}\n")
        f.write(f"Recall: {results['Recall']:.4f}\n")
        f.write(f"F1 Score: {results['F1 Score']:.4f}\n")
        f.write("\n")

In [110]:
import joblib

# Menyimpan model (dapat diubah jika sudah disimpan sebelumnya)
# joblib.dump(logreg_model, 'logreg_model.pkl')
# joblib.dump(tree_model, 'tree_model.pkl')
# joblib.dump(knn_model, 'knn_model.pkl')

print("Model telah disimpan.")

Model telah disimpan.


##Menyiapkan Lingkungan Kerja

In [111]:
import os
import pandas as pd
from sklearn.preprocessing import StandardScaler
import requests

# Fungsi untuk memastikan folder ada
def ensure_directory_exists(directory):
    if not os.path.exists(directory):
        os.makedirs(directory)

# Mengunduh dataset
def download_data(url, save_path):
    response = requests.get(url)
    with open(save_path, 'wb') as file:
        file.write(response.content)

# Proses data
def preprocess_data(input_path, output_path):
    data = pd.read_csv(input_path)
    X = data.iloc[:, :-1]
    y = data.iloc[:, -1]

    # Normalisasi fitur
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    processed_data = pd.DataFrame(X_scaled, columns=X.columns)
    processed_data['class'] = y

    # Simpan data yang telah diproses
    processed_data.to_csv(output_path, index=False)

if __name__ == "__main__":
    # Pastikan folder yang diperlukan ada
    ensure_directory_exists('data/raw')
    ensure_directory_exists('data/processed')

    url = "https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"
    download_data(url, 'data/raw/iris.csv')
    preprocess_data('data/raw/iris.csv', 'data/processed/processed_data.csv')

In [112]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
import joblib


def ensure_directory_exists(directory):
    if not os.path.exists(directory):
        os.makedirs(directory)

def train_and_save_models(data_path):
    data = pd.read_csv(data_path)
    X = data.iloc[:, :-1]
    y = data['class']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    models = {
        "logreg_model": LogisticRegression(random_state=42),
        "tree_model": DecisionTreeClassifier(random_state=42),
        "knn_model": KNeighborsClassifier(n_neighbors=5)
    }

    ensure_directory_exists('models')

    for name, model in models.items():
        model.fit(X_train, y_train)
        joblib.dump(model, f'models/{name}.pkl')

if __name__ == "__main__":
    train_and_save_models('data/processed/processed_data.csv')

In [113]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import joblib

# Fungsi untuk evaluasi model
def evaluate_models(data_path):
    data = pd.read_csv(data_path)
    X = data.iloc[:, :-1]
    y = data['class']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    models = {
        "logreg_model": joblib.load('models/logreg_model.pkl'),
        "tree_model": joblib.load('models/tree_model.pkl'),
        "knn_model": joblib.load('models/knn_model.pkl')
    }

    results = []
    for name, model in models.items():
        y_pred = model.predict(X_test)
        results.append({
            "Model": name,
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred, average='weighted'),
            "Recall": recall_score(y_test, y_pred, average='weighted'),
            "F1 Score": f1_score(y_test, y_pred, average='weighted')
        })

    # Simpan hasil evaluasi
    with open('results/model_evaluation_results.txt', 'w') as f:
        for result in results:
            f.write(f"Model: {result['Model']}\n")
            f.write(f"Accuracy: {result['Accuracy']:.4f}\n")
            f.write(f"Precision: {result['Precision']:.4f}\n")
            f.write(f"Recall: {result['Recall']:.4f}\n")
            f.write(f"F1 Score: {result['F1 Score']:.4f}\n")
            f.write("\n")

if __name__ == "__main__":
    evaluate_models('data/processed/processed_data.csv')


In [114]:
import os
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
import joblib

# Fungsi untuk memastikan folder ada
def ensure_directory_exists(directory):
    if not os.path.exists(directory):
        os.makedirs(directory)

# Fungsi untuk evaluasi model
def evaluate_models(data_path):
    data = pd.read_csv(data_path)
    X = data.iloc[:, :-1]
    y = data['class']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    models = {
        "logreg_model": joblib.load('models/logreg_model.pkl'),
        "tree_model": joblib.load('models/tree_model.pkl'),
        "knn_model": joblib.load('models/knn_model.pkl')
    }

    results = []
    for name, model in models.items():
        y_pred = model.predict(X_test)
        results.append({
            "Model": name,
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred, average='weighted'),
            "Recall": recall_score(y_test, y_pred, average='weighted'),
            "F1 Score": f1_score(y_test, y_pred, average='weighted')
        })

    # Pastikan folder untuk menyimpan hasil evaluasi ada
    ensure_directory_exists('results')

    # Simpan hasil evaluasi
    with open('results/model_evaluation_results.txt', 'w') as f:
        for result in results:
            f.write(f"Model: {result['Model']}\n")
            f.write(f"Accuracy: {result['Accuracy']:.4f}\n")
            f.write(f"Precision: {result['Precision']:.4f}\n")
            f.write(f"Recall: {result['Recall']:.4f}\n")
            f.write(f"F1 Score: {result['F1 Score']:.4f}\n")
            f.write("\n")

if __name__ == "__main__":
    evaluate_models('data/processed/processed_data.csv')

data_prep.py

In [117]:
import os
import pandas as pd
import requests

def download_data(url, dest_folder):
    if not os.path.exists(dest_folder):
        os.makedirs(dest_folder)
    response = requests.get(url)
    file_path = os.path.join(dest_folder, 'data.csv')
    with open(file_path, 'wb') as file:
        file.write(response.content)
    print(f"Data downloaded to {file_path}")

def preprocess_data(file_path):
    data = pd.read_csv(file_path)
    data = data.dropna()
    processed_file_path = file_path.replace('.csv', '_processed.csv')
    data.to_csv(processed_file_path, index=False)
    print(f"Data processed and saved to {processed_file_path}")

if __name__ == "__main__":
    data_url = "https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"
    data_folder = "data"
    download_data(data_url, data_folder)
    preprocess_data(os.path.join(data_folder, 'data.csv'))

Data downloaded to data/data.csv
Data processed and saved to data/data_processed.csv


##evaluation

In [120]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import joblib

def train_model(data_path):
    data = pd.read_csv(data_path)
    X = data.iloc[:, :-1]
    y = data['variety']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = RandomForestClassifier()
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    print(f"Model accuracy: {accuracy:.2f}")

    model_file_path = "models/model.pkl"
    joblib.dump(model, model_file_path)
    print(f"Model saved to {model_file_path}")

if __name__ == "__main__":
    data_file_path = "data/data_processed.csv"  # Ganti dengan jalur data Anda
    train_model(data_file_path)


Model accuracy: 1.00
Model saved to models/model.pkl


##deploy


In [121]:
from flask import Flask, request, jsonify
import joblib
import pandas as pd

app = Flask(__name__)
model = joblib.load('models/model.pkl')

@app.route('/predict', methods=['POST'])
def predict():
    data = request.get_json()
    df = pd.DataFrame(data)
    predictions = model.predict(df)
    return jsonify(predictions.tolist())

if __name__ == "__main__":
    app.run(port=5000)

 * Serving Flask app '__main__'
 * Debug mode: off


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
